name: Build and test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Run Svelte checks
        env:
          PUBLIC_BASE_URL: https://traquantopassa.in
        run: npm run check
      - name: Run tests
        run: npm run test
